### ISSUE TITLE
How to add an additional button actions, eg. publish, unpublish?

### ISSUE THREAD

**Issue by chriscalip** [yajra/laravel-datatables-editor#1]
### Summary of problem or feature request

Model has an attribute named "status" its binary 0 or 1. 0 for false, 1 for true.

How how add another action? Yajra\DataTables\DataTablesEditor->actions = ['create', 'edit', 'remove', 'publish', 'unpublish']

publish gets to set selected records as status 1
unpublish gets to set selected records as status 0.

**Comment by chriscalip** [comment]
Implemented via:
`
class AssetsDataTablesEditor extends DataTablesEditor{
    protected $model = Asset::class;
    protected $actions = ['create', 'edit', 'remove', 'publish'];
    public function publish(Request $request){ ...
    public function publishing(Model $model, array $data){...
`
`
class AssetsDataTable extends DataTable{
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->parameters([
                        'dom' => 'Bfrtip',
                        'order' => [1, 'asc'],
                        'select' => [
                            'style' => 'os',
                            'selector' => 'td:first-child',
                        ],
                        'buttons' => [
                            ['extend' => 'create', 'editor' => 'editor'],
                            ['extend' => 'edit', 'editor' => 'editor'],
                            ['extend' => 'remove', 'editor' => 'editor'],
                            ['extend' => 'publish', 'editor' => 'editor'],
                        ]
                    ]);
    }
`

Getting console error:
`uncaught exception: Cannot extend unknown button type: publish`

**Comment by yajra** [comment]
IMO, you need to create a custom publish button for this to work. See https://datatables.net/extensions/buttons for docs.

**Comment by chriscalip** [comment]
Right, looks like its on the client side. I'll update this issue when i finish this task and give gist examples for future readers.

**Comment by yajra** [comment]
In case you still need it, I just tried to play with this and come up with a workaround solution as posted on https://datatables.net/forums/discussion/46517/extend-remove-button-and-change-mode-to-rename-the-action#latest.

**Comment by yajra** [comment]
BTW, since you using the html plugin, you would also need to update to [html - v3.5.0](https://github.com/yajra/laravel-datatables-html/pull/49) for better editor support. This is how it was added using html builder:

```php
                            [
                                'extend' => 'selected',
                                'action' => "function ( e, dt, node, config ) {
                                    var formData = {
                                        action: 'publish',
                                        data: $.map(dt.rows({selected: true}).data(), function (o) {
                                            return o.DT_RowId;
                                        })
                                    };
                                    
                                    $.post(editor.s.ajax, formData)
                                        .then(function(response) {
                                            dt.draw(false);
                                        })
                                    
                                }",
                            ],
```

**Comment by chriscalip** [comment]
For future readers here's a rough draft example showcasing an additional button "Publish"
https://gist.github.com/chriscalip/46ee6a32264eb6184b5800e0e1bcd8a7
