### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by BardoQi** [yajra/laravel-datatables-editor#12]
### Summary of problem or feature request

  Problem 1
    - yajra/laravel-datatables-buttons 3.0.x-dev requires maatwebsite/excel ^2.0
 -> satisfiable by maatwebsite/excel[2.0.1, 2.0.11, 2.0.7, 2.0.8, 2.1.10, 2.1.11
, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.1.18, 2.1.19, 2.1.20, 2.1.21
, 2.1.22, 2.1.23, 2.1.24, 2.1.25, 2.1.26, 2.1.27, 2.1.28, 2.1.4, 2.1.5, 2.1.6, 2
.1.7, 2.1.8, 2.1.9, 2.1.x-dev, v2.0.0, v2.0.10, v2.0.2, v2.0.3, v2.0.4, v2.0.5,
v2.0.6, v2.0.9, v2.1.0, v2.1.1, v2.1.2, v2.1.3] but these conflict with your req
uirements or minimum-stability.
    - yajra/laravel-datatables-editor v1.0.0 requires yajra/laravel-datatables-b
uttons 3.* -> satisfiable by yajra/laravel-datatables-buttons[3.0.x-dev].
    - Installation request for yajra/laravel-datatables-editor 1.0 -> satisfiabl
e by yajra/laravel-datatables-editor[v1.0.0].

Installation failed, reverting ./composer.json to its original content.

### System details

- Operating System  
- PHP Version 7.1
- Laravel Version 5.5
- Laravel-DataTables Version  8.0

**Comment by karmendra** [comment]
Refer issue #10 , looks like the same thing you are seeking.
