### ISSUE TITLE
Error Message Attribute

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables-editor#13]
Datatables Editor error messages are showing the field name itself.

![image](https://user-images.githubusercontent.com/11293052/43326670-0ebe15a2-91d7-11e8-80ba-f0e686a01bbd.png)

In laravel we have option to override attribute display name as following in `class UserRequest extends Request {`

	public function attributes()
	{
		return [
			'name'                  => 'Name',
			'password'              => 'Password',
			'password_confirmation' => 'Retype Password',
			'email'                 => 'Email ID',
		];
	}

How can I do this for datatables editor?

- Operating System Ubuntu 16.06
- PHP Version 7.1
- Laravel Version 5.6
- Laravel-DataTables Version Latest ("yajra/laravel-datatables": "^1.0",  "yajra/laravel-datatables-editor": "^1.1")

**Comment by yajra** [comment]
Do you want to change the error message or just the field attribute name? I recently added a custom message handler but not sure yet about the attributes name. I think this is not yet supported.

**Comment by karmendra** [comment]
Thanks for your response, let me see if I can do a PR for this.

**Comment by karmendra** [comment]
I created a PR #14 for this.
