### ISSUE TITLE
Edit without HTML tags.

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables-editor#2]
I did editColumn for name column to show as strong text. When I attempt to edit the name filed using the datatables editor, name field appears with html tags. Attached is an image showing the issue.

I am using the latest version of Yajra Datatables and Datatables Editor.
I was reading thru this old issue where similar issue was fixed for export files, `https://github.com/yajra/laravel-datatables/issues/341` . This might be bit more challenging then that. 

Please suggest what is the best way to deal with this.

![edit_showing_html](https://user-images.githubusercontent.com/11293052/35610573-ce6e4b82-0687-11e8-9485-086f35950e61.png)

**Comment by yajra** [comment]
Does the name attribute contains an html stored on the database or it's just presented like that? It the original value does not contain html, then I suggest you just add a column where presentation is applied?

```php
->addColumn('name_html', "<strong>{{$name}}</strong>"
```

**Comment by karmendra** [comment]
The value in db is store as `User`, I applied the presentation using the editColumn function 

	public function dataTable($query)
	{
		return datatables($query)
			->setRowId('id')
			->addColumn('password', '')
			->editColumn('verified', function ($user) {
				return $user->verified ? 'Yes' : 'No';
			})
			->editColumn('created_at', function ($user) {
				return $user->created_at ? with(new Carbon($user->created_at))->format('M d, Y H:i:s') : '';
			})
			->editColumn('updated_at', function ($user) {
				return $user->updated_at ? with(new Carbon($user->updated_at))->format('M d, Y H:i:s') : '';
			})
			->filterColumn('created_at', function ($query, $keyword) {

				$date_range = explode('-', $keyword);
				if (!empty($date_range[0]) || !empty($date_range[1])) {
					try {
						$dates[] = Carbon::parse(
							trim($date_range[0]))->startOfDay()->toDateTimeString();
						$dates[] = Carbon::parse(
							trim($date_range[1]))->endOfDay()->toDateTimeString();
						$query->whereBetween('created_at', [$dates[0], $dates[1]]);
					} catch (\Exception $e) {
					}
				}
			})
			->editColumn('roles.name', function ($user) {
				return $user->roles->pluck('name')->implode('');
			})
			->editColumn('name', function ($user) {
				return '<strong>'.$user->name.'</strong>';
			})
			->rawColumns(['name', 'action'])
			->addColumn('action', 'users.actions');
	}

I even tried as you suggested, it didn't help

Replaced 

			->editColumn('name', function ($user) {
				return '<strong>'.$user->name.'</strong>';
			})

with

			->editColumn('name', '<strong>{{$name}}</strong>')

**Comment by drbyte** [comment]
@karmendra note the difference between what @yajra posted and what you posted:

```diff
- ->editColumn('name', '<strong>{{$name}}</strong>')
+ ->addColumn('name_html', "<strong>{{$name}}</strong>")
```

Probably also have to change:
```diff
- 		->rawColumns(['name', 'action'])
+		->rawColumns(['name_html', 'action'])
```

**Comment by karmendra** [comment]
okay, that way (using addColumn) html is applied while display but while edit it will take the value of the name. I think this makes sense, I will try this and post my results here.
