### ISSUE TITLE
Support Editor 1.8

### ISSUE THREAD

**Issue by schonhoff** [yajra/laravel-datatables-editor#20]
General asking:

Are you considering to support Datatables Editor 1.8? It has some new JS methodes that would help me in a special case (the ajax() method for example,).  It would be awesome if you can update the packages needed :+1: 

Link to the release notes:
https://editor.datatables.net/download/1.8.0

Thanks for the awesome packages already! Helped me out a lot!

**Comment by yajra** [comment]
Will definitely support it when I got the chance. Can you post some snippets on how you used it for ref? Thanks!

**Comment by yajra** [comment]
BTW, I just recently released an editor integration on html generator package in case you are using it.

See PR https://github.com/yajra/laravel-datatables-html/pull/73 for details.

**Comment by schonhoff** [comment]
I have the html generator package loaded but for me sometimes it breaks my code. Sadly, I had to use self-written code. But thanks for the update, I will try it in another project. 

Back to the main topic:

I'm currently not using 1.8 because I need you to update your package. I don't integrate the Editor myself. I'm very thankful that you are considering it and hopefully you can update it without a big change :)

**Comment by yajra** [comment]
I just realized that I am already using the latest version 1.8 when I was making the PR mentioned above.  In that case, I can say that the package should work on it.

**Comment by schonhoff** [comment]
I updated my Editor files and it worked :+1:  I don't see any errors or warnings. This can be closed and thanks a lot for the great work!
