### ISSUE TITLE
Adding more than one row

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables-editor#3]
Hi,
I am using DataTables editor to add CRUD permissions.
UI looks as shown in attached image, where user selects the CRUD option and then just gives Table name e.g.
when table name is "tester" than four rows are added in permissions table with "tester-create", "tester-read", "tester-update" and "tester-delete" permissions.

I am not able to do that using creating() callback in PermissionsDataTablesEditor class. I tried following code.

	public function creating(Model $model, array $data)
	{
		if ($data['crud']) {
			$module = $data['table_name'];
			unset($data);
			$data = [];
			foreach (['create', 'read', 'update', 'delete'] as $permissionValue) {
				$data[] = [
					'name'         => $module . '-' . $permissionValue,
					'display_name' => ucfirst($permissionValue) . ' ' . ucfirst($module),
					'description'  => ucfirst($permissionValue) . ' ' . ucfirst($module),
				];
			}
			return $data;
		} else {
			return $data;
		}
	}

Problem is, it is using create() and not insert().
Please suggest what is the best way to do it, if code changes are required I will code and submit a PR.

![image](https://user-images.githubusercontent.com/11293052/37758958-1cc972ee-2dd8-11e8-9d3e-429c438febc0.png)

Thanks,
Karmendra

**Comment by yajra** [comment]
I think you are trying to insert 4 records on permission? If that is the case, I think you need to override the create function and do your custom logic there.

```php
public function create(Request $request)
```

**Comment by karmendra** [comment]
yep my bad, I used the incorrect callback, like you said correct function to use is `create`
