### ISSUE TITLE
Datatables Editor Formatters

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables-editor#33]
Do we support [Datatables Editor Formatters](https://editor.datatables.net/manual/php/formatters)?

If so please let me know where to start.

**Comment by yajra** [comment]
I think this is not yet supported. You can start this with the [html](https://github.com/yajra/laravel-datatables-html) builder package and check the integration with `Field` class.

**Comment by yajra** [comment]
@karmendra I didn't quite get the documentation for formatters. Do you have a working example on how you implemented this?

**Comment by karmendra** [comment]
I do not have any working example. Where I needed this was if User inputs a date in `DD-MM-YYYY` format in editor form, before model is saved it should be converted to `YYYY-MM-DD hh:mm:ss` format, which is accepted by mysql datetime column. and when we get date from database we convert it to `DD-MM-YYYY` format before displaying it in edit form to User.

These Formatters are part of Datatable Editor's PHP library, see [Datatables Editor PHP Library Documentation](https://editor.datatables.net/docs/1.8.0/php/namespace-DataTables.Editor.html) for more details. As far as I know you are not using that library for yajra/laraveldatatables-editor implementation. 

We are having `editColumn` and `rawColumns` functions to do formatting of cell value before display in Datatable. but editor there is no such option.

**Comment by yajra** [comment]
@karmendra sent a PR https://github.com/yajra/laravel-datatables/pull/2193, kindly review if you have spare time.

For editor field date for instance, you can already do the format. 

```
Fields\Date::make('start_at')->format('d-m-Y'),
```

When saving the date, you just need to cast start_at as date and thus no need to format it since Laravel will automatically handle it for us.

**Comment by markplus** [comment]
> @karmendra sent a PR [yajra/laravel-datatables#2193](https://github.com/yajra/laravel-datatables/pull/2193), kindly review if you have spare time.
> 
> For editor field date for instance, you can already do the format.
> 
> ```
> Fields\Date::make('start_at')->format('d-m-Y'),
> ```
> 
> When saving the date, you just need to cast start_at as date and thus no need to format it since Laravel will automatically handle it for us afaik.

If I add this --> Fields\Date::make('start_at')->format('d-m-Y'),  the table disappears

[[](url)](https://datatables.net/forums/uploads/editor/g8/aut7i6i8ciyb.png)
