### ISSUE TITLE
yajrabox.com is down... where can we find some doc ?

### ISSUE THREAD

**Issue by Benoit75** [yajra/laravel-datatables-editor#34]
### Summary of problem or feature request

Thank's for your amazing code. 
It's hard to use whithout docs or example 
because Your server  (yajrabox.com) is down. 

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-DataTables Version

**Comment by peterkeri** [comment]
Same problem, it's still down.

**Comment by MagicTrixor** [comment]
Still down - is there another source I can view the documentation? Thanks.
