### ISSUE TITLE
Pivot table support

### ISSUE THREAD

**Issue by bitrevo** [yajra/laravel-datatables-editor#42]
Currently we do not have editor action to attach or detach record to Laravel pivot table, any plan to support it?

In my application, I have user groups and each user group can attach or detach members from it, I have this implementation currently and like to migrate to datatables editor.
```php
$data->users()->updateExistingPivot($user->id, $validated);
```

**Comment by yajra** [comment]
I think you can already implement this using `saved` event hook. For instance, I have this role-permissions relationship and was able to save the pivots.

![image](https://user-images.githubusercontent.com/2687997/66021526-9483f900-e51d-11e9-9ddf-f552289d2ebd.png)

```php
// Editor script
                    ->editors(
                        Editor::make()
                              ->fields([
                                  Fields\Field::make('name'),
                                  Fields\Field::make('slug')
                                              ->multiEditable(false)
                                              ->fieldInfo('If left blank, value will be generated based on name.'),
                                  Fields\Checkbox::make('permissions[].id')
                                                 ->modelOptions(Permission::class, 'name')
                                                 ->label('Permissions'),
                              ])
                              ->language(Lang::get('datatables'))
                    );

```

Editor saved event hook:

```php
    /**
     * @param Model|Role $model
     * @param array $data
     * @return Role
     */
    public function saved($model, $data)
    {
        $model->syncPermissions(data_get($data, 'permissions.*.id', []));

        return $model;
    }
```

**Comment by bitrevo** [comment]
Thanks for sharing, it make sense.
However, I decided to create a model for my pivot table, it helps simplify below actions:
- Retrieve JSON data from user group members table.
- Attach and detach group members, no additional code needed.
- Return updated data back to datatables, for  updating display value.

The event hooks really useful for display related data on the pivot datatable. e.g. user name and group name.
```php
public function saved(Model $model, array $data)
{
	$model->setAttribute('user', $model->user);
	$model->setAttribute('user_group', $model->userGroup);
	return $model;
}
```
