### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by denis-kopelevich** [yajra/laravel-datatables-editor#47]
https://github.com/yajra/laravel-datatables-editor/blob/master/src/DataTablesEditor.php#L112

```php
    /**
     * @return string
     */
    protected function getUseFriendlyErrorMessage()
    {
        return 'An error occurs while processing your request.';
    }
```
Should be getUse**r**FriendlyErrorMessage

**Comment by yajra** [comment]
Yes, definitely a typo. Can you send a PR to fix the method name? A possible breaking bug fix but I guess it can be considered to be just bug version bump. Thanks!
