### ISSUE TITLE
Editor 2.0.0 released

### ISSUE THREAD

**Issue by schonhoff** [yajra/laravel-datatables-editor#56]
Hey,

I just want to say that the editor is released in a new major version. 
https://editor.datatables.net/download/2.0.0
There should not be any issue with this package.

I tried it myself and had no issue.

Maybe it will be necessary in future bug reports to say which version of editor someone is using.

**Comment by yajra** [comment]
Wow, thanks for the heads up. Will give Editor 2.0 a try too.

**Comment by karmendra** [comment]
Is Editor v2 support now?

**Comment by yajra** [comment]
Yes, I've been using v2.0.5 for quite some time already.

**Comment by yajra** [comment]
Ow latest is 2.0.8, checking it too. But anyways, it's already supported.
