### ISSUE TITLE
Unable to install editor datatables by composer require yajra/laravel-datatables-editor:^1.0

### ISSUE THREAD

**Issue by mayuri-acesnws** [yajra/laravel-datatables-editor#63]
composer require yajra/laravel-datatables-editor:^1.0 
After this its giving this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install illuminate/validation 5.5.x-dev|don't install laravel/framework v8.54.0
    - don't install illuminate/validation 5.5.x-dev|remove laravel/framework v8.54.0
    - don't install illuminate/validation 5.5.x-dev|don't install laravel/framework v8.54.0
    - yajra/laravel-datatables-editor v1.0.0 requires illuminate/validation 5.5.* -> satisfiable by illuminate/validation[5.5.x-dev].
    - Installation request for yajra/laravel-datatables-editor 1.0 -> satisfiable by yajra/laravel-datatables-editor[v1.0.0].
    - Installation request for laravel/framework v8.54.0 -> satisfiable by laravel/framework[v8.54.0].

Installation failed, reverting ./composer.json to its original content.

- Operating System Windows 10
- PHP Version 7.4
- Laravel Version 854
- Laravel-DataTables Version 9.18

**Comment by mayuriak** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install illuminate/validation 5.5.x-dev|don't install laravel/framework v8.54.0
    - don't install illuminate/validation 5.5.x-dev|remove laravel/framework v8.54.0
    - don't install illuminate/validation 5.5.x-dev|don't install laravel/framework v8.54.0
    - yajra/laravel-datatables-editor v1.0.0 requires illuminate/validation 5.5.* -> satisfiable by illuminate/validation[5.5.x-dev].
    - Installation request for yajra/laravel-datatables-editor 1.0 -> satisfiable by yajra/laravel-datatables-editor[v1.0.0].
    - Installation request for laravel/framework v8.54.0 -> satisfiable by laravel/framework[v8.54.0].


Installation failed, reverting ./composer.json to its original content.
