### ISSUE TITLE
datatables editor select2 - Uncaught Error: Error adding field - unknown field type select2

### ISSUE THREAD

**Issue by matteocostantini** [yajra/laravel-datatables-editor#81]
### Summary of problem
 I've a Laravel 9 installation, in dev console show Uncaught Error: Error adding field - unknown field type select2.
Before working but after asset build with mix not!
 Can you provide a guideline to check my integration ? Select2 before work perfectly,  in my laravel project not commits changing anything!!!

- Operating System win11 pro dev
- PHP Version 8.1
- Laravel Version 9
- Laravel-DataTables Version 9

**Comment by markplus** [comment]
I have the same problem and haven't been able to solve it yet
