### ISSUE TITLE
Edit but create new

### ISSUE THREAD

**Issue by markplus** [yajra/laravel-datatables-editor#82]
Good morning, when you go to edit, if I wanted to create a new record leaving the existing one, how could I do it? Edit and save but add and not remove the existing one, can this be done?
Save a copy of the existing one

```
 public function editRules(Model $model): array
    {
        return [
           'id',
           'name'
        ];
    }
```
- Operating System linux
- PHP Version 8.2
- Laravel Version 10.10
- Laravel-DataTables Version 10.1

**Comment by yajra** [comment]
Yes, you can create a duplicate button for this. See https://github.com/yajra/laravel-datatables-vite/blob/main/js/buttons/duplicate.js for ref.

**Comment by markplus** [comment]
Thanks for the reply, but where should I enter this code? should I create the file in the directory I view?
```
yajra/laravel-datatables-vite/tree/main/js/buttons)/duplicate.js
```
