### ISSUE TITLE
Uploading files and images

### ISSUE THREAD

**Issue by markplus** [yajra/laravel-datatables-editor#84]
### Summary of problem or feature request

I couldn't figure out how to upload files and images with the editor. I'm doing some tests but I always get the same error, is there a guide or documentation to understand how to do it? I need to enable uploading of pdf files and images but I'm completely stuck and don't understand how to do it

### Code snippet of problem

<!--
Fields\File::make('allegato')->type('upload'),
```
-->

### System details

- Operating System Linux
- PHP Version 8.2
- Laravel Version 10
- Laravel-DataTables Version 10.1
- Laravel-DataTables Editor Version 1.25

**Comment by yajra** [comment]
Use the `File` or `Image` field, then set some [upload rules](https://yajrabox.com/docs/laravel-datatables/10.0/editor-rules#upload-rules). Inspect the ajax request to see the payload. Unfortunately, it's not well-documented atm. Thanks!

```php
Fields\Image::make('avatar')
  ->fieldInfo('The image must be square and at least 200x200 pixels.'),
```
